version: '3.8'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=https://www.sii.cl/valores_y_fechas/uf/uf
      
  test:
    build: .
    volumes:
      - .:/code
    environment:
      - BASE_URL=https://www.sii.cl/valores_y_fechas/uf/uf
