version: '3.8'
services:
  web:
    container_name: api_uf_backend
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=https://www.sii.cl/valores_y_fechas/uf/uf
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_api_uf
    ports:
      - "6379:6379"

  test:
    build: .
    volumes:
      - .:/code
    environment:
      - BASE_URL=https://www.sii.cl/valores_y_fechas/uf/uf
